### PR TITLE
feat: Implement pre commit hook

### PR DESCRIPTION
**Pull request by SavGRY**
Refering to #74 

So I closed by mistake the #74 so I reopened this PR, refer to the old PR for the comments. 

Hi! I saw that in the project were not implemented a code linter, so I decided to add a simple eslint configuration.
Alongside the linter I also added a pre-commit hook using lefthook. I took inspiration from the [Pokerogue lefthook file](https://github.com/pagefaultgames/pokerogue/blob/main/lefthook.yml) and adapted it to the needs of this project.
I did omit the typescript implementation considering that this project has none.

If you want to run the linter "standalone" I've created an alias in the package.json under lint so whenever you run in the cli npm run lint it will run the eslint . command (if you want all the commands in the cli just refer to the [eslint doc](https://eslint.org/docs/latest/use/command-line-interface) ).

Last but not least, I made some changes to the code after i ran the linter in order to be compliant with the new implementation.

I've briefly tested the game to make sure that the changes I made doesn't make the project exploding

### CODE REVIEW

**Comment by SavGRY** [comment]
I'll rewrite my last comment on the #74 MR

>Oh I think I see what might've been going on. I didn't add new variables to the export list towards the bottom of the files; I forgot that was a thing since that wasn't my code heh. Maybe try running it again with the new changes from main?

Sorry for the late response but it was a busy weekend. So, I ran the pre-commit hooks in the MR rebased on the synced main, and in the file you mentioned the only thing that changed was the spacing (from 4 spaces to 2 as [w3school suggests here](https://www.w3schools.com/js/js_conventions.asp)). In all the other files ran by the hook, if there was an unused var that doesn't match the pattern (it has to start with _ to make it "private") it will be deleted. I'm gonna push the latest work.

Thank you for your patient :)

**Comment by Admiral-Billy** [comment]
Seems solid to me, and nothing seems to be "gone" this time around. I'm pretty much ready to merge it, but just to clarify what this is, this'll basically take commits and clean up the formatting and such before they actually get commited? And there's also the manual command that can be run for the same thing?

**Comment by SavGRY** [comment]
> Seems solid to me, and nothing seems to be "gone" this time around. I'm pretty much ready to merge it, but just to clarify what this is, this'll basically take commits and clean up the formatting and such before they actually get commited? And there's also the manual command that can be run for the same thing?

Yep. This's called a "hook". Basically it _can_ be used to performe the cleaning of the code with the rules you specify, for instance with the `eslint` file to be inline with the code conventions. 
You can also add a hook for the `pre-push`, so whenever you're going to push to the branch it will perform some action, it's often used to run test.

Or, if you want you can run whatever you want in the `lefthook.yaml` file under the `command` option.

If you want to run it manually, I've also created the command in the `package.json` file.

**Comment by Admiral-Billy** [comment]
Gotcha, thanks for letting me know :)

I was running it to test it out and it seems to do the job.

**Pull request merged**
