### PR TITLE
Large Cleanup + Added an 'about' tab

### PR DESCRIPTION
**Pull request by artman41**
* Moved all tabs to separate `.js` files
* Separated out common concerns into `global.js`, `utils.js` & `tabmenu.js` files
* Added a new 'About' tab which will compare the last downloaded tag vs the latest on github

### CODE REVIEW

**Comment by artman41** [comment]
@Admiral-Billy I'll rebase it once you're done making improvement 😄 

Just let me know when you're done pushing 😛

**Comment by Admiral-Billy** [comment]
Oh hey, just now saw this sorry! I'm done with changes for now heh, was fixing a mac bug by editing the offline-mode-status stuff.

The changes are looking very nice, although I do notice a few issues:

1. Downloading files doesn't seem to work; I think it's trying to download directly to resources and is failing because the app's own resources are there; it at least needs to be downloading to a secondary folder I think.
2. The update app button in the about menu is downloading the latest game files; it should probably either say "Update game files" or be reworked to somehow snag the latest release from GitHub of the app.
3. The preload script seems to not be running for one reason or another. This one I'm not sure the reason for, but it does seem to be an error: 
image

I think everything else is fine though, as far as I can tell. The code definitely looks a lot nicer now :)

**Comment by artman41** [comment]
> Oh hey, just now saw this sorry! I'm done with changes for now heh, was fixing a mac bug by editing the offline-mode-status stuff.
> 
> The changes are looking very nice, although I do notice a few issues:
> 
> 1. Downloading files doesn't seem to work; I think it's trying to download directly to resources and is failing because the app's own resources are there; it at least needs to be downloading to a secondary folder I think (either app/game like it was doing before, or whatever else sounds good like just plain "game" and also changing the gameDir stuff in globals.js)
> 2. The update app button in the about menu is downloading the latest game files; it should probably either say "Update game files" or be reworked to somehow snag the latest release from GitHub of the app.
> 3. The preload script seems to not be running for one reason or another. This one I'm not sure the reason for, but it does seem to be an error:
>    image
> 
> I think everything else is fine though, as far as I can tell. The code definitely looks a lot nicer now :)

strange, I'll try to take a peek - could be something to do with windows since I was doing the dev on a linux machine

I'll grab node on my windows pc and give it a go 👍

**Comment by artman41** [comment]
* `preload.js` - simple fix, moved it to `src/`
* Update button - renamed to 'Update Game files' and clarified the version info, will look at adding the app version too
* Downloading the game - unsure if it's supposed to, but it seems to be downloading it to `./app/game` which looks correct? Basing this off of 
```javascript
let gameDir = (function() {
    if (process.platform === 'darwin') {
        // For macOS, use the user's Documents directory
        return path.join(app.getPath('documents'), 'PokeRogue', 'game');
    } else {
        // For other platforms, use the app's directory
        return path.join(__dirname, '..', 'app', 'game');
    }
})();
```

technically we could drop this somewhere else but depends what you have in mind

**Comment by artman41** [comment]
@Admiral-Billy rebased and made a handful more changes

* I noticed when developing on Linux that you assumed Discord would always be available - I've added an initial connect to detect whether it's there and, if so, we continue with the rich presence like before
* I've added the Current & Latest App versions to the About box
* I've added the code _commented out_ to download the App - I'm not entirely sure what the best approach to do this would be so I've hidden to button from the About box for now

Other than the `gameDir` stuff, I think we're in a good place if you'd like to merge this in 👍

**Comment by Admiral-Billy** [comment]
Alright, so based on a bit of debugging, it looks like it's trying to extract directly into the app.asar rather than the app subfolder that it used to. Changing it to `return path.join(__dirname, '../..', 'app', 'game');` in globals seems to have fixed the issue heh.

The only other issue I see now is that the offline mode setting doesn't enable itself after downloading, and I'm not actually sure why, since it looks like you're checking that appropriately to me. Any ideas?

**Comment by artman41** [comment]
> Alright, so based on a bit of debugging, it looks like it's trying to extract directly into the app.asar rather than the app subfolder that it used to. Changing it to `return path.join(__dirname, '../..', 'app', 'game');` in globals seems to have fixed the issue heh, but we can just simplify that to a game folder and get rid of the app.
> 
> The only other issue I see now is that the offline mode setting doesn't enable itself after downloading, and I'm not actually sure why, since it looks like you're checking that appropriately to me. Any ideas? It works with a restart, but ideally it should immediately update.

Intriguing one that, I'll have a look and see what I can find 🤔

**Comment by Admiral-Billy** [comment]
I think technically the directory the game is searching from is within app.asar, so when you put the files in their own little src folder they went one level deeper than the originally were, hence having to add the extra .. to the file path.

The only issue I see now is that the menu got weird at the top, with different ordering + a debug option (I think?). I went ahead and fixed those real quick though, so I believe we're good to go. Thanks for the help! :)

**Comment by Admiral-Billy** [comment]
The only thing I'm noticing right now after some fixes is that for some reason the "About" tab doesn't actually show up on Mac at all; it works on Windows + Linux as you expect, and everything else about the Mac version works as intended too. Any ideas why that might be?

**Pull request merged**
