### PR TITLE
feat: Implement pre commit lint hook

### PR DESCRIPTION
**Pull request by SavGRY**
Hi! I saw that in the project were not implemented a code linter, so I decided to add a simple eslint configuration.
Alongside the linter I also added a pre-commit hook using `lefthook`. I took inspiration from the [Pokerogue lefthook file](https://github.com/pagefaultgames/pokerogue/blob/main/lefthook.yml) and adapted it to the needs of this project. 
I did omit the typescript implementation considering that this project has none.

If you want to run the linter "standalone" I've created an alias in the `package.json` under `lint` so whenever you run in the cli `npm run lint` it will run the `eslint .` command (if you want all the commands in the cli just refer to the [eslint doc](https://eslint.org/docs/latest/use/command-line-interface) ).

Last but not least, I made some changes to the code after i ran the linter in order to be compliant with the new implementation.

I've briefly tested the game to make sure that the changes I made doesn't make the project exploding

### CODE REVIEW

**Comment by SavGRY** [comment]
I adjusted the order of the file commited, i made a slight mistake ehehe

**Comment by Admiral-Billy** [comment]
It seems like lint might be trying to fix stuff from downloaded game files/built app files if you happen to have those when running it, is there a way to make it avoid those? Also, can we add the formatting that turns tabs into 4 spaces (or vice versa) kinda like the PokeRogue version has? It's not something I care about personally but the consistency in the project would be nice so I don't have to manually fix it heh.

Other than that, seems solid enough to me. App behavior seems to be about the same as expected (although checking over the commits, it seems like there's some weird deletions like horizontalTypeChartWindow? They still function, so presumably they're in other files somewhere, but it messes up the organization a bit.).

**Comment by SavGRY** [comment]
> It seems like lint might be trying to fix stuff from downloaded game files/built app files if you happen to have those when running it, is there a way to make it avoid those? Also, can we add the formatting that turns tabs into 4 spaces (or vice versa) kinda like the PokeRogue version has? It's not something I care about personally but the consistency in the project would be nice so I don't have to manually fix it heh.
> 
> Other than that, seems solid enough to me. App behavior seems to be about the same as expected (although checking over the commits, it seems like there's some weird deletions like horizontalTypeChartWindow? They still function, so presumably they're in other files somewhere, but it messes up the organization a bit.).

If you want eslit ignoring some folders / files, it's just matter of inserting the path in the `ignore` array (line 12 of `eslint.config.mjs` 2nd commit). 
If you provide me the path you would like to ignore, I'll put them in the codebase.
Personally I'm not a huge fan of 4 spaces indents in a JS project but surely I can configure it. 

The `horizontalTypeChartWindow` has been deleted because it was declared but never used, as well as all the other deletetion in the codebase.

**Comment by Admiral-Billy** [comment]
> The `horizontalTypeChartWindow` has been deleted because it was declared but never used, as well as all the other deletetion in the codebase.

This part confuses me, because it definitely is called in utilities_tab.js: 

```javascript
// Create the horizontal type chart window
function createHorizontalTypeChartWindow() {
    globals.horizontalTypeChartWindow = utils.createWindow({
        width: 1300,
        height: 600,
        icon: 'icons/PR',
        autoHideMenuBar: true,
        webPreferences: {
            nodeIntegration: true
        }
    });

    globals.horizontalTypeChartWindow.loadFile('type-chart-2.png');

    globals.horizontalTypeChartWindow.on('close', (event) => {
        if (globals.horizontalTypeChartWindow && !globals.closeUtilityWindows) {
            event.preventDefault();
            globals.horizontalTypeChartWindow.hide(); // Hide the window instead of closing it
        } else {
            globals.horizontalTypeChartWindow = null;
        }
        if (globals.mainWindow) {
            globals.mainWindow.focus();
        }
    });
}```

As for the lint config, tabs are totally fine too; just as long as there's consistency. In terms of paths to ignore, it would just be the "dist" folder if it happens to exist.

**Comment by Admiral-Billy** [comment]
Oh I think I see what might've been going on. I didn't add new variables to the export list towards the bottom of the files; I forgot that was a thing since that wasn't my code heh. Maybe try running it again with the new changes from main?

**Comment by SavGRY** [comment]
> Oh I think I see what might've been going on. I didn't add new variables to the export list towards the bottom of the files; I forgot that was a thing since that wasn't my code heh. Maybe try running it again with the new changes from main?

Sorry for the late response but it was a busy weekend. So, I ran the pre-commit hooks in the MR rebased on the synced main, and in the file you mentioned the only thing that changed was the spacing (from 4 spaces to 2 as [w3school suggests here](https://www.w3schools.com/js/js_conventions.asp)). In all the other files ran by the hook, if there was an unused var that doesn't match the pattern (it has to start with `_` to make it "private") it will be deleted. I'm gonna push the latest work. 

Thank you for your patient :)

**Pull request closed without merging**
