### PR TITLE
Minor QOL improvements

### PR DESCRIPTION
**Pull request by podarsmarty**
- Updated about window's parent so that it doesn't get locked and move when the main window is being moved.
- Put downloads of files into a submenu
- Updated storage location of game files on mac so that it does not add to your documents folder
- Removed edit menu that is unused
- Added shortcut to mute the game (seems to be a bug in the main game when using modifier key with m or esc that the game will bring up and close the menu repeatedly if you are in a state where it can be opened. hitting esc or m will stop this)

### CODE REVIEW

**Comment by Admiral-Billy** [comment]
The edit menu is unused in the app itself, but it's there because it allows the hotkeys to function normally (I had someone on a Mac complain about certain functions not working because of that, although I forget which ones specifically; probably had something to do with the login page).

Other than that, seems solid, nicely done :)

**Comment by Admiral-Billy** [comment]
Here's the issue in question: #5

**Comment by podarsmarty** [comment]
ahhh interesting usecase. only thing i had thought of was potentially copying errors

**Comment by podarsmarty** [comment]
@Admiral-Billy hmm bit unfortunate electron doesn't natively support actions without a menu. tested hiding the menu but it doesn't seem to work with accelerators even when it should be enabled. Pulled in a diff library to register local shortcuts rather than registering/unregistering global shortcuts manually.

i've only tested it on mac fyi

**Comment by Admiral-Billy** [comment]
Oops, I got distracted and forgot to check this out!

As far as I can tell, on Windows at least this seems to be double pasting whenever I use ctrl+V. I'm not actually sure why that's happening from a quick glance over the code though; it *seems* fine.

**Comment by podarsmarty** [comment]
hmm i wonder if electron on windows doesn't need the shortcuts defined for textbox things to be passed through. ill have to setup a dev env on my windows machine to test

@Admiral-Billy did you test it on linux? wondering if it behaves same as windows

**Comment by podarsmarty** [comment]
@Admiral-Billy aight, confirmed my suspicions on windows. the shortcuts pass through electron without them being defined. only add the shortcuts for non-windows. might need to do it for mac only but dont have a linux install to test

**Comment by Admiral-Billy** [comment]
I haven't tested it on Linux yet but I'll give it a go on my Steam Deck a bit later tonight to see if that behaves differently

IIRC from when I initially tested it it was only Mac that needed the extra shortcuts, but of course I'll double check that.

**Pull request merged**
